name: dmc_server_frog
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  crypto: ^3.0.6
  dart_frog: ^1.1.0
  excel: ^4.0.6
  mysql_client: 0.0.27
  shelf_cors_headers: ^0.1.5
  uuid: ^4.5.1

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.25.8
